### ISSUE TITLE
QPress documentation or examples 

### ISSUE THREAD

**Issue by mayaalmaraz** [SWotherspoon/QPress#2]
Hi, I am excited to use QPress for a qualitative modeling project I am working on. I am pretty new to R/Github and am having some trouble finding documentation or examples of how to use the package. I was wondering is someone might be able to point me in the right direction. Would really appreciate it! Thanks!

**Comment by raymondben** [comment]
Hi - the documentation can be browsed online at https://swotherspoon.github.io/QPress/
There are examples in the form of vignettes, which would normally also be shown at that same URL, but for boring technical reasons currently aren't. But you can view the vignettes from within R:
```
devtools::install_github("swotherspoon/QPress", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)
```
And then:
```
vignette("Snowshoe")
vignette("Mesocosm")
```

(Edited 3-Jul to add `build_opts` arg)

**Comment by mayaalmaraz** [comment]
Awesome. Thanks so much!

**Comment by brunj7** [comment]
Hi there,

I am getting an error when trying to run the above lines:

```
Warning message:
vignette ‘Snowshoe’ not found 
```

**Comment by mayaalmaraz** [comment]
Thanks so much for you response @raymondben! I am also having trouble loading the package. Both of the following commands are giving me an error message. Any advice? Thanks in advance!

devtools::install_github("SWotherspoon/QPress”)

devtools::install_github("swotherspoon/QPress", build_vignettes = TRUE)

**Comment by raymondben** [comment]
Hi @mayaalmaraz - could you please copy the error message here, and also the output of `sessionInfo()`?

**Comment by raymondben** [comment]
@brunj7 - try:
```
devtools::install_github("swotherspoon/QPress", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)
```
Apparently the `build_opts` includes `--no-build-vignettes` by default, which I'd missed (though it worked for me without that - maybe I had an old devtools/remotes?).
You may also need to add `force = TRUE` to force it to reinstall the package.

**Comment by mayaalmaraz** [comment]
Thanks for your responses @raymondben and @brunj7 ! Here are the errors I am getting when I try each of six suggested commands:

Attempt #1 
>devtools::install_github("SWotherspoon/QPress")

* installing *source* package ‘QPress’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
ERROR: lazy loading failed for package ‘QPress’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/QPress’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/tq/l9l5w8cs71g1kp0zslwwywgc0000gp/T//Rtmp1iwwAL/file2baa2b9d50f6/QPress_0.21.tar.gz’ had non-zero exit status

Attempt #2
> library(QPress)
Error in library(QPress) : there is no package called ‘QPress’

Attempt #3 
> devtools::install_github("swotherspoon/QPress", build_vignettes = TRUE)

* installing *source* package ‘QPress’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
ERROR: lazy loading failed for package ‘QPress’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/QPress’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/tq/l9l5w8cs71g1kp0zslwwywgc0000gp/T//Rtmp1iwwAL/file2baa53559032/QPress_0.21.tar.gz’ had non-zero exit status

Attempt #4
> devtools::install_github("swotherspoon/QPress", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)

 ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error : .onLoad failed in loadNamespace() for 'tcltk', details:
     call: fun(libname, pkgname)
     error: X11 library is missing: install XQuartz from xquartz.macosforge.org
   ERROR: lazy loading failed for package ‘QPress’
─  removing ‘/private/var/folders/tq/l9l5w8cs71g1kp0zslwwywgc0000gp/T/RtmpeXG4al/Rinst394052067255/QPress’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

Attempt #5
> devtools::install_github("swotherspoon/QPress", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE, force = TRUE)

    ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error : .onLoad failed in loadNamespace() for 'tcltk', details:
     call: fun(libname, pkgname)
     error: X11 library is missing: install XQuartz from xquartz.macosforge.org
   ERROR: lazy loading failed for package ‘QPress’
─  removing ‘/private/var/folders/tq/l9l5w8cs71g1kp0zslwwywgc0000gp/T/RtmpgmQgaD/Rinst396337a4a9c/QPress’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

Attempt #6
> sessionInfo()

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      rstudioapi_0.8    magrittr_1.5      usethis_1.5.0    
 [5] devtools_2.0.2    pkgload_1.0.2     R6_2.2.2          rlang_0.2.2      
 [9] tools_3.5.1       pkgbuild_1.0.3    sessioninfo_1.1.1 cli_1.1.0        
[13] withr_2.1.2       remotes_2.0.4     yaml_2.2.0        assertthat_0.2.0 
[17] digest_0.6.17     rprojroot_1.3-2   crayon_1.3.4      processx_3.3.1   
[21] callr_3.2.0       fs_1.2.6          ps_1.3.0          curl_3.2         
[25] memoise_1.1.0     glue_1.3.0        compiler_3.5.1    desc_1.2.0       
[29] backports_1.1.2   prettyunits_1.0.2

**Comment by mayaalmaraz** [comment]
@raymondben and @brunj7 I was able to get the package to load. yay! Turns out I didn't have Xquartz. I am still unable to get the vignettes to work but I will try some other strategies  in the mean time. Thanks for you help!

**Comment by raymondben** [comment]
@mayaalmaraz @brunj7 just FYI I've converted the vignettes to rmarkdown format, which means that they (a) should be more likely to install properly, but also (b) you can just browse them in the pkgdown documentation at https://swotherspoon.github.io/QPress/
