### ISSUE TITLE
Constraining range of community matrix values

### ISSUE THREAD

**Issue by mfisher5** [SWotherspoon/QPress#5]
I'm working on a qualitative network model where we are interested in characterizing edges as high / low strength in addition to positive / negative. I'm hoping to customize the QPress code to run this way, by constraining the range from which randomized edge weights can be chosen -- so for example, *high* positive edges could range from (0.5,1) and *low* positive edges could range from (0,0.5). I think that I have identified where in the `community_sampler` function this could be done (below), but was wondering if this had ever been brought up before and/or if there might be a better way of achieving the same outcome with the existing QPress functions. Thank you!

```
## example edges df
edges <- parse.digraph(c(
  "E *-> D",
  "D *-> C",
  "C -> E",
  "E *-> B",
  "B *-> A",
  "A -> E",
  "D --> B"))
edges$Type2 <- c(rep("H",3),rep("L",4),rep("H",7),rep("L",2))  # NEW - high / low


community.sampler <- function(edges,required.groups=c(0)) {
  n.nodes <- length(node.labels(edges))
  weight.labels <- edge.labels(edges)
  n.edges <- nrow(edges)
  W <- matrix(0,n.nodes,n.nodes)
  
  ## Ranges and indices of non-zero matrix entries
  lower <- ifelse((edges$Type=="U" | edges$Type=="N") & edges$Type2=="H",-1L,
                ifelse((edges$Type=="U" | edges$Type=="N") & edges$Type2=="L",-0.5,
                       ifelse(edges$Type2=="H", 0.5, 0L)))        #lower bound of range (-1/-0.5, 0/0.5)
  upper <- ifelse((edges$Type=="U" | edges$Type=="P") & edges$Type2=="H", 1L,
                ifelse((edges$Type=="U" | edges$Type=="P") & edges$Type2=="L", 0.5,
                       ifelse(edges$Type2=="H", -0.5, 0L)))      #upper bound of range (-0.5/0, 0.5/1)
  k.edges <- as.vector(unclass(edges$To)+(unclass(edges$From)-1)*n.nodes) 
...

```

**Comment by SWotherspoon** [comment]
I strongly strongly recommend against this.  I think this makes sense only in very very special circumstances. The weights are more abstract than this process would suggest.  If you must adopt this approach, I would recommend drawing the weights from appropriate beta distributions.

There is some prototype code in another branch that allows for constrained sampling, where a partial order can be imposed on the magnitude of the weights.  But again, I think this only makes sense in some extremely special circumstances.

**Comment by mfisher5** [comment]
Ok thank you!
