### ISSUE TITLE
Frequency table values from impact.barplot

### ISSUE THREAD

**Issue by mcmahsta** [SWotherspoon/QPress#6]
I've made a series of bar plots using impact.barplot() representing a collection of press scenarios on a model read in from Dia. I'm wondering if it's possible to somehow extract the frequency table values represented in the plots as a data frame to use with ggplot, or if there's another/better way to try and do that to plot these results a bit differently? Thanks!

**Comment by raymondben** [comment]
Hi @mcmahsta, you can use the `impact.barplot0` function for this. It will produce the plot but also return the result as a matrix. Some example ggplot code (adapted from the shiny app in the package):
```
library(ggplot2)
library(QPress)
modelA <- parse.digraph(c("V-*V", "P-*P", "V*->H", "H*->P"))
simA <- system.simulate(1000, modelA)

imres <- impact.barplot0(simA, perturb = 1)

## to data frame
outcome_levels <- c("-", "0", "+")
imres <- setNames(as.data.frame(imres), outcome_levels)

## convert to long format
imres <- do.call(rbind, lapply(seq_len(ncol(imres)), function(z) data.frame(node = rownames(imres), outcome = colnames(imres)[z], n = imres[, z], stringsAsFactors = FALSE)))
imres$outcome <- factor(imres$outcome, levels = outcome_levels)

## ggplot it
pal <- c("#92C5DE", "#808080", "#F4A582")
ggplot(imres, aes_string(x = "node", y = "n", group = "node", fill = "outcome")) + geom_col() +
     coord_flip() +
     scale_fill_manual(values = setNames(pal, outcome_levels), name = "Outcome") +
     theme_bw() + labs(y = "Simulations", x = "")

**Comment by mcmahsta** [comment]
Excellent, thank you! I was using the node selector with impact.barplot, how do you create the perturb vector in  this case to indicate which nodes are being pressed? Is that part of the parse.digraph function, or something else?

**Comment by raymondben** [comment]
I think (it's been a while, hope this is correct) you just put the node numbers:

**Comment by raymondben** [comment]
I think (it's been a while, hope this is correct) that you just give a named vector, e.g.:
```
imres <- impact.barplot0(simA, perturb = c(H = -1, V = 1))
```
will negatively press H and (simultaneously) positively press V. And equivalent syntax for `monitor` if you are using that

**Comment by mcmahsta** [comment]
That worked! Thank you!
